version: '3.1'

services:
  db:
    image: postgres
    container_name: test_nest
    restart: always
    environment:
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - .development.env
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: